// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtN7DakJeBqj39VXO9v1lqchETKK7UY2Q',
    appId: '1:644738007899:web:9888175b15dca84b89d07e',
    messagingSenderId: '644738007899',
    projectId: 'elnemr-57623',
    authDomain: 'elnemr-57623.firebaseapp.com',
    storageBucket: 'elnemr-57623.appspot.com',
    measurementId: 'G-682HC60C8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqYwLBfAReIca2H7yvXkm-TdKkWwGd_4',
    appId: '1:644738007899:android:81cc5f41eedb66d989d07e',
    messagingSenderId: '644738007899',
    projectId: 'elnemr-57623',
    storageBucket: 'elnemr-57623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3kIqm0SdbbzbvhVkjVUsIXlJU82mYLbs',
    appId: '1:644738007899:ios:689a078ef25a1ee889d07e',
    messagingSenderId: '644738007899',
    projectId: 'elnemr-57623',
    storageBucket: 'elnemr-57623.appspot.com',
    iosClientId: '644738007899-65i119m59apngijn941ldrsusov6cfe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.elnemrInvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3kIqm0SdbbzbvhVkjVUsIXlJU82mYLbs',
    appId: '1:644738007899:ios:689a078ef25a1ee889d07e',
    messagingSenderId: '644738007899',
    projectId: 'elnemr-57623',
    storageBucket: 'elnemr-57623.appspot.com',
    iosClientId: '644738007899-65i119m59apngijn941ldrsusov6cfe9.apps.googleusercontent.com',
    iosBundleId: 'com.example.elnemrInvoice',
  );
}
